sudo: false
language: python
dist: focal
python:
  - "3.10"
branches:
  only:
    - master
before_install:
  - git fetch --unshallow --tags
install: pip install tox-travis
script: tox
after_success:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then sh semantic-release.sh; fi'